%{
static char rcsid[] = "$Id: pvload.y,v 1.1 2011/11/19 01:24:43 tcsuuser Exp $";

/*+*********************************************************************
  Module:       pvload.{y,c}

  Author:       W. Lupton

  Description:  yacc definitions for pv (EPICS process variable) loader
		(pvload) and saver (pvsave)


  Notes:	1. This module contains the main program and parser, and
		   includes the file pvload_lex.c, which is automatically
		   generated by lex from the file pvload_lex.l.

		2. All interactions with channel access are performed by
		   routines in the file pvloadLib.c. Either ezca (under
		   Unix) or ca (under Unix or vxWorks) can be used, under
		   control of the EZCA macro.

		3. The pvload and pvsave programs are the same Unix binary,
		   which must be invoked as "pvload" or "pvsave". Under
		   VxWorks there are separate pvload() and pvsave() entry
		   points.

		4. Both versions read a file (see "Grammar") of process
		   variable assignments. pvload sets the process variables
		   to the values in the file. pvsave uses it as a template
		   and writes an output file of the same format but with the
		   variable values replaced with the current ones read from
		   the online system.

		5. Special "%" lines are treated as comments by pvload
		   (although they must still be syntactically correct)
		   and force pvsave to behave (just for that line) as
		   though it is pvload. Thus pvsave can write channels
		   (sometimes necessary in order to place the correct
		   values in other channels). If a "%" line does not
		   have an "=", the value if the channel is read and
		   is then used as the value for the channel on the next
		   line that does _not_ start with a "%". This allows
		   pvsave to read values from "readback" channels and
		   generate commands to write those values to "control"
		   channels. An example of this is given below.

		6. Special "*" lines simply have the "*" ignored and the
		   rest of the line passed to the output file. They can
		   therefore be used for pvsave applications where neither
		   the readback of the current channel value nor the
		   value of a previous channel is appropriate (this is
		   not a very well thought-out facility; in the future,
		   the "*" may be handled more like the "%", i.e. passed
		   through to the output file).

		7. Syntax errors and errors opening input or output files
		   are propagated to the environment. This is not currently
		   true of channel access errors, which will be reported but
		   which will not return an overall failure status.


  Invocation:	1. The Unix utilities have the following invocation:

		   pvload [<input>] [<subs>] [-d]
		   pvsave [<input>] [<subs>] [<output>] [-o <output>] \
					     [-d] [-t] [-f]

		   <input>  is the input file (positionally first argument),
			    stdin if omitted

		   <subs>   is a set of macro substitution strings of the
			    form "a=a_value,b=b_value"; see "Macros" for
			    more details

		   <output> is the pvsave output file, stdout if omitted

		   [-d]	    enables debug output; this echoes the parsed
			    input to stdout; for pvsave, current channel
			    values are reported (NB, if pvsave is in any
			    case outputting to stdout, the -d flag has no
			    effect)

		   [-t]     (pvsave only) truncates the output file to zero
			    length (default is to append)

		   [-f]     (pvsave only) fails if the output file exists

		2. The VxWorks-callable routines (NB, these routines are
		   also available in libpvload.a under Unix) have the
		   following invocations:

		   int pvload(
		       char *file,     name of file containing list of
				       PV assignments (if NULL, stdin is
				       used)

		       char *subst,    list of macro substitutions of
				       the form "a=b, c=d", where "$(a)"
				       references macro a (can be NULL);
				       if it includes "version=xxx",
				       version will be added to
				       fopenData() search list

		       int flags );    extra flags:
					1 bit => debugging ("-d")
					2 bit => no CA init
					4 bit => abort shell on error

		   int pvsave(
		       char *file,     name of template file containing
				       list of PV assignments in pvload
				       format (if NULL, stdin is used)

		       char *subst,    same as pvload...

		       char *outFile,  name of output file to contain
				       copy of input file with current
				       channel values substituted (if
				       NULL, stdout is used)

		       int flags );    extra flags:
					1 bit => debugging ("-d")
					2 bit => no CA init
					4 bit => abort shell on error
				        8 bit => truncate output ("-t")
				       16 bit => fail if output exists ("-f")


   Macros:	1. Both versions support macro substitutions within process
		   variable names (but not within values). The standard $(var)
		   syntax is used. Macro substitution uses macLib.

		2. If a "version" macro is defined, its value is used as part
		   of the search path that locates input files and determines
		   where to place output files (currently ignored by the Unix
		   version). See "Searching" for details.


  Searching:    1. Under VxWorks (and only if the FOPENDATA macro is
		   defined), an fopenData() routine (supplied with the
		   distribution) is used to locate input files and to
		   determine where to place output files. This routine
		   is somewhat Keck-specific, as is the pvload code that
		   sets the search path.

		2. fopenData() is like fopen() but has two extra arguments,
		   a colon-separated search path and the address of a string
		   to receive the full name of the located file (optional).


  Grammar:	1. Comments are introduced by "#" characters and cause
		   the rest of the line to be ignored. White space is
		   similarly ignored.

		2. Lines introduced by "%" characters behave like comments
		   with pvload but cause temporary pvload-like behavior
		   for pvsave (see the Notes above and the Example below).

		3. pvsave files may contain the special string "$pvsaveLog".
		   If so, the line following this string will indicate the
		   user, host and UTC time.

		4. The file consists of a set of EPICS process variable
		   assignments, with a syntax reminiscent of C. For
		   example:

		   int fred.VAL = 1;

		   sets fred.VAL to an integer 1.

		5. Arrays are supported, as illustrated by the following:

		   double xxx.VAL[3] = { 0.1, 0.2, 0.3 };

		   Individual elements can be addressed (useful for long
		   arrays to avoid typing mistakes) as in:

		   double yyy[2] = {
		       [0] 4.5e8,
		       [1] 6.8e9
		   };

		   (the braces around the array value are optional)

		6. Scalar strings are supported but not (yet) string arrays.

		7. Values can be followed by units specifiers (implemented as
		   numeric scale factors). For example, the units specifier
		   "mm" is the same as "* 0.001" and converts the value in
		   the file from millimeters to meters (on the assumption that
		   the value in the database is in meters). Supported units
		   are "arcsec" (or "arcsecs"), "degrees" (or "deg"), "um"
		   (or "microns"), "mm" (or "millimeters") and "m" (or
		   "meters"). Units specifiers can be preceded by "*" (implicit
		   if omitted) or "/". Units specifiers are not supported for
		   strings.

		8. Process variables can be grouped, which means that no
		   attempt is made to set any of them until the end of the
		   group has been seen, and then the entire group is processed
		   before anything else is done. The use of grouping is
		   recommended. For example:

		   group {
		       int fred = 1;
		       double jim[5] = { 1, 2, 3, 4, 5 };
		   };

		   (only ezca groups are used; problems were encountered with
		   CA groups and their use is suppressed in the code)

		9. There should be a complete list of the syntax, but there
		   isn't.

   Examples:	1. A hypothetical example mostly to check lexical analysis
		   (note that channel type defaults to "double")

		    group {
			int $(aaa).VAL = 1;
			double $(bbb) = 2;
			ccc[4] = {
			    [0] -3.5e-4 * 1e4,
			    [2] 5 deg,
			    [1] -4 arcsec,
			    [3] 6 7
			};
			ddd[3] = { 0.1, 0.2, 0.3 };
		    };
		    
		    string ddd = "freddy";
		    eee = 7;

		2. A simple example used for testing pvsave. Note that
		   "pvload -d" or "pvsave" output can be piped into either
		   tool, which is a useful sanity check. For example, I
		   just did the following:

		   % pvload <file> -d | pvsave | pvsave | pvload

		   pvsave attempts to retain file layout. In particular,
		   it retains comments and white space at the beginning of
		   lines. It doesn't retain other white space and does a
		   poor job with multi-line arrays!

		    # Sample input file for pvload EPICS PV loader program
		    
		    # full line comment
		    group {
		    
			# indented comment
			int    k0:dcs:chp:azGain.VAL = 1000;
			string k0:dcs:chp:elGain.VAL = "1";
		    
			# array layout is not preserved by pvsave (sorry)
			int    k0:dcs:chp:ec:inquire[4] = {
				    [0] 0,
				    [1] 1,
				    [2] 42, 43
			};
		    };
		    
		    # $pvsaveLog$

		3. An example to demonstrate use of "%" and "*" lines.
		   Here "*" lines are used to pass some channel assignments
		   verbatim to the output (see the earlier discussion of
		   "*" in the Notes) and "%" lines are used to select inputs
		   (query.J) and to fetch values from one channel that are to
		   be written to another channel. All that's needed now is
		   a looping facility...

		    %k0:dcs:dev1:query.J = 0;
		    group {
			%string k0:dcs:dev1:query.VALA;
			 string k0:dcs:dev1:control.A = "";
			%string k0:dcs:dev1:query.VALB;
			 double k0:dcs:dev1:control.B = 0.0;
			*long   k0:dcs:dev1:defCmd = 1;
		    }
		     
		    %k0:dcs:dev1:query.J = 1;
		    group {
			%string k0:dcs:dev1:query.VALA;
			 string k0:dcs:dev1:control.A = "";
			%string k0:dcs:dev1:query.VALB;
			 double k0:dcs:dev1:control.B = 0.0;
			*long   k0:dcs:dev1:defCmd = 1;
		    }

  *********************************************************************/

/* Include files */
#include <stdio.h>
#include <string.h>

#include "macLib.h"
#include "epicsPrint.h"
#ifdef vxWorks
#include <logLib.h>
#endif

#include "pvload.h"

/* Definitions to avoid need for Keck knl.h */
#ifndef FALSE
#define FALSE 0
#endif
#ifndef TRUE
#define TRUE 1
#endif

#define PI              (3.141592653589793238462643)
#define D2R(angle)      ((angle)*PI/180.0)
#define AS2R(angle)     ((angle)*PI/(3600.0*180.0))

/* Open file with search path (Keck-specific) */
FILE *fopenData( char *file, char *type, char *search, char *path );

/* Macro for opening a data file (only use fopenData() under VxWorks and
   if the FOPENDATA macro is defined) */
#if defined(vxWorks) && defined(FOPENDATA)
#define FOPEN(_file,_type,_sear) fopenData(_file,_type,_sear,NULL)
#else
#define FOPEN(_file,_type,_sear) fopen(_file,_type)
#endif

/* Forward declarations */
static int work();
static int yyerror();

/* Static variables */
static int line_num = 1;
%}

/* Start symbol */
%start file

/* Token declarations */
%token <Int>  tokenINTEGER
%token <Real> tokenREAL
%token <Str>  tokenGROUP tokenSLEEP tokenARCSECS tokenDEGREES
%token <Str>  tokenUM tokenMM tokenM tokenTYPE
%token <Str>  tokenPVNAME tokenSTRING

/* Union to be used for values */
%union {
    int	   Int;
    double Real;
    char   *Str;
}

%%
/******************************************************************************/
/* Start of rules */

/* The entire file consists of a list of items */
file
	:	file item
	|	item
	|	/* empty */
	;

/* An item is either a group, a single item or a sleep declaration */
item
	:	group
	|	single
	|	sleep
	;

/******************************************************************************/
/* A group is a grouped list of single items */
group
	:	group_head '{' group_body '}' group_tail
	{
		pvloadEndGroup();
	}
	;

group_head
	:	tokenGROUP
	{
		pvloadStartGroup();
	}
	;

group_body
	:	group_body single
	|	single
	|	/* empty */
	;

group_tail
	:	';'
	|	/* empty */
	;

/******************************************************************************/
/* A single item looks a bit like a C declaration and assignment */
single
	:	single_head single_equals single_body ';'
	{
		pvloadEndVariable();
	}
	|	single_head ';'
	{
		pvloadEndVariable();
	}
	;

single_head
	:	single_start single_type single_name single_count
	;

single_start
	:	/* empty */
	{
		pvloadStartVariable( FALSE );
	}
	|	'%'
	{
		pvloadStartVariable( TRUE );
	}
	;

single_type
	:	tokenTYPE
	{
		pvloadType( $<Str>1 );
		free( ( void * ) $<Str>1 );
	}
	|	/* empty */
	;

single_name
	:	tokenPVNAME
	{
		pvloadName( $<Str>1 );
		free( ( void * ) $<Str>1 );
	}
	;

single_count
	:	'[' tokenINTEGER ']'
	{
		pvloadCount( $<Int>2 );
	}
	|	/* empty */
	;

single_equals
	:	'='
	{
		pvloadEquals();
	}

single_body
	:	single_indval
	|	single_bodyn
	|	'{' single_bodyn '}'
	;

single_bodyn
	:	single_indval
	|	single_bodyn ',' single_indval
	;

single_indval
	:	single_index single_value single_scale
	;

single_index
	:	'[' tokenINTEGER ']'
	{
		pvloadIndex( $<Int>2 );
	}
	|	/* empty */
	{
		pvloadIndex( -1 );
	}
	;

single_value
	:	tokenINTEGER
	{
		pvloadValue( ( double ) $<Int>1 );
	}
	|	tokenREAL
	{
		pvloadValue( $<Real>1 );
	}
	|	tokenSTRING
	{
		pvloadString( $<Str>1 );
		free( ( void * ) $<Str>1 );
	}
	;

single_scale
	:	'*' tokenINTEGER
	{
		pvloadScale( NULL, ( double ) $<Int>2 );
	}
	|	'*' tokenREAL
	{
		pvloadScale( NULL, $<Real>2 );
	}
	|	'/' tokenINTEGER
	{
		pvloadScale( NULL, ( $<Int>2 == 0 ) ? 1.0 :
						      1.0 / ( double ) $<Int>2);
	}
	|	'/' tokenREAL
	{
		pvloadScale( NULL, ( $<Real>2 == 0.0 ) ? 1.0 : 1.0 / $<Real>2 );
	}
	|	tokenINTEGER
	{
		pvloadScale( NULL, ( double ) $<Int>1 );
	}
	|	tokenREAL
	{
		pvloadScale( NULL, $<Real>1 );
	}
	|	'/' tokenARCSECS
	{
		pvloadScale( "/ arcsec", 1.0 / AS2R( 1.0 ) );
	}
	|	tokenARCSECS
	{
		pvloadScale( "arcsec", AS2R( 1.0 ) );
	}
	|	'/' tokenDEGREES
	{
		pvloadScale( "/ deg", 1.0 / D2R( 1.0 ) );
	}
	|	tokenDEGREES
	{
		pvloadScale( "deg", D2R( 1.0 ) );
	}
	|	'/' tokenUM
	{
		pvloadScale( "/ um", 1.0 / 0.000001 );
	}
	|	tokenUM
	{
		pvloadScale( "um", 0.000001 );
	}
	|	'/' tokenMM
	{
		pvloadScale( "/ mm", 1.0 / 0.001 );
	}
	|	tokenMM
	{
		pvloadScale( "mm", 0.001 );
	}
	|	'/' tokenM
	{
		pvloadScale( "/ m", 1.0 / 1.0 );
	}
	|	tokenM
	{
		pvloadScale( "m", 1.0 );
	}
	|	/* empty */
	{
		pvloadScale( NULL, 1.0 );
	}
	;

/******************************************************************************/
/* Sleep causes a delay of a specified length (default 1s) */
sleep
	:	tokenSLEEP ';'
	{
		pvloadSleep( 1.0 );
	}
	|	tokenSLEEP tokenINTEGER ';'
	{
		pvloadSleep( ( double ) $<Int>2 );
	}
	|	tokenSLEEP tokenREAL ';'
	{
		pvloadSleep( $<Real>2 );
	}
	;
%%
/******************************************************************************/
/* Start of code */

#include "pvload_lex.c"

#ifdef linux
/* Unix main program (may be invoked as "pvload" or "pvsave") */
int
main(
    int argc,			/* (>) argument count */

    char *argv[] )		/* (>) pointers to argument strings */
{
    int status = 0;		/* return status */

    char *slash;		/* pointer to last slash in command name */

    char *cmd;			/* pointer to command name in argv[0] */

    int isPvload, isPvsave;	/* booleans determining whether command is
				   pvload or is pvsave */


    FILE *fd;			/* fd for input file */

    char *file = NULL;		/* name of file containing list of PV
				   assignments (if NULL, stdin is used) */

    char *subst = NULL;		/* list of macro substitutions of the form
				   "a=b, c=d", where "$(a)" references
				   macro a (can be NULL) */

    char *outFile = NULL;	/* output file for pvsave (defaults to
				   standard output) */

    int flags = 0;		/* extra flags (pvload and pvsave):
				     1 bit => debugging ("-d")
				   extra flags (pvsave only):
				     8 bit => truncate output ("-t")
				    16 bit => fail if output exists ("-f") */

    int i;			/* counter */

    /* determine whether being called as pvload or pvsave */
    slash = strrchr( argv[0], '/' );
    if ( slash == NULL )
	cmd = argv[0];
    else
	cmd = slash + 1;
    isPvload = ( strcmp( cmd, "pvload" ) == 0 );
    isPvsave = ( strcmp( cmd, "pvsave" ) == 0 );
    if ( !isPvload && !isPvsave ) {
	epicsPrintf( "%s: command must be pvload or pvsave\n", cmd );
	return -1;
    }

    /* parse ( argc, argv ) arguments to same form as those passed directly
       under vxWorks (no "-n" because it's dangerous in a standalone program) */
    for ( i = 1; i < argc; i++ ) {
	if ( argv[i][0] == '-' ) {
	    if ( strcmp( argv[i], "-d" ) == 0 )
		flags |= OPT_DEBUG;
	    else if ( isPvsave && strcmp( argv[i], "-t" ) == 0 )
		flags |= OPT_TRUNCATE;
	    else if ( isPvsave && strcmp( argv[i], "-f" ) == 0 )
		flags |= OPT_FAIL;
	    else if ( isPvsave && strcmp( argv[i], "-o" ) == 0 ) {
		if ( i == argc - 1 ) {
		    epicsPrintf( "%s: -o must be followed by output file\n",
			         cmd, argv[i] );
		    return -1;
		}
		outFile = argv[++i];
	    }
	    else
		epicsPrintf( "%s: illegal option %s ignored\n", cmd, argv[i] );
	}
	else if ( file == NULL ) {
	    file = argv[i];
	}
	else if ( subst == NULL ) {
	    subst = argv[i];
	}
	else if ( isPvsave && outFile == NULL ) {
	    outFile = argv[i];
	}
	else {
	    epicsPrintf( "%s: argument %s ignored\n", cmd, argv[i] );
	}
    }

    /* call common work routine */
    status = work( isPvload, file, subst, outFile, flags, FALSE );

    return status;
}
#endif /* linux */

/* vxWorks shell-callable pvload routine (c.f. dbLoadRecords) */
int
pvload(
    char *file,			/* (>) name of file containing list of PV
				       assignments (if NULL, stdin is used) */

    char *subst,		/* (>) list of macro substitutions of the form
				       "a=b, c=d", where "$(a)" references
				       macro a (can be NULL); if it includes
				       "version=xxx", version will be added to
				       fopenData() search list */

    int flags )			/* (>) extra flags:
					1 bit => debugging ("-d")
					2 bit => no CA init
					4 bit => abort shell on error */
{
    return work( TRUE, file, subst, NULL, flags );
}

/* vxWorks shell-callable pvsave routine (c.f. dbLoadRecords) */
int
pvsave(
    char *file,			/* (>) name of template file containing list
				       of PV assignments in pvload format (if
				       NULL, stdin is used) */

    char *subst,		/* (>) list of macro substitutions of the form
				       "a=b, c=d", where "$(a)" references
				       macro a (can be NULL); if it includes
				       "version=xxx", version will be added to
				       fopenData() search list */

    char *outFile,		/* (>) name of output file to contain copy
				       of input file with current channel
				       values substituted (if NULL, stdout
				       is used) */

    int flags )			/* (>) extra flags:
					1 bit => debugging ("-d")
					2 bit => no CA init
					4 bit => abort shell on error
				        8 bit => truncate output ("-t")
				       16 bit => fail if output exists ("-f") */
{
    return work( FALSE, file, subst, outFile, flags );
}

/* work routine called by both pvload() and pvsave() */
static int
work(
    int isPvload,		/* (>) TRUE if pvload; FALSE if pvsave */

    char *file,			/* (>) name of input file (if NULL, stdin
				       is used) */

    char *subst,		/* (>) list of macro substitutions of the form
				       "a=b, c=d", where "$(a)" references
				       macro a (can be NULL); if it includes
				       "version=xxx", version will be added to
				       fopenData() search list */

    char *outFile,		/* (>) name of output file, ignored for
				       pvload (if NULL, stdout is used) */

    int flags )			/* (>) extra flags (pvload and pvsave):
					1 bit => debugging ("-d")
					2 bit => no CA init
					4 bit => abort shell on error
				       extra flags (pvsave only):
				        8 bit => truncate output ("-t")
				       16 bit => fail if output exists ("-f") */
{
    static int count = 0;	/* keeps track of number of times called */

    int status = 0;		/* return status */

    char *cmd;			/* command name, pvload or pvsave */

    MAC_HANDLE *substHandle;	/* macro substitution handle */

    char substVersion[128];	/* substituted value of $(version) macro */

    char substEcVers[128];	/* substituted value of $(ecvers) macro */

    char search[512];		/* fopenData() search path */

    FILE *fd=NULL;		/* fd for input file */

    FILE *outFd=NULL;		/* fd for output file */

    /* command name for messages */
    cmd = ( isPvload ) ? "pvload" : "pvsave";

    /* if a macro substitution string was supplied, initialize macro
       substitution routines */
    substHandle = NULL;
    if ( subst != NULL && *subst != '\0' ) {
	char **pairs;
	if ( macCreateHandle( &substHandle, NULL ) < 0 ) {
	    status = -1;
	    goto error;
	}
	if ( macParseDefns( substHandle, subst, &pairs ) < 0 ) {
	    status = -1;
	    goto error;
	}
	if ( macInstallMacros( substHandle, pairs ) < 0 ) {
	    free( pairs );
	    status = -1;
	    goto error;
	}
	free( pairs );
    }

#if defined(vxWorks) && defined(FOPENDATA)
    /* check for $(version) macro */
    strcpy( substVersion, "$(version)" );
    if ( substHandle != NULL ) {
	char buff[80];
	macSuppressWarning( substHandle, TRUE );
	if ( macExpandString( substHandle, substVersion,
			      buff, sizeof( buff ) ) < 0 ) {
	    status = -1;
	    goto error;
	}
	macSuppressWarning( substHandle, FALSE );
	strcpy( substVersion, buff );
    }

    /* check for $(ecvers) macro: epcom version */
    strcpy( substEcVers, "$(ecvers)" );
    if ( substHandle != NULL ) {
	char buff[80];
	macSuppressWarning( substHandle, TRUE );
	if ( macExpandString( substHandle, substEcVers,
			      buff, sizeof( buff ) ) < 0 ) {
	    status = -1;
	    goto error;
	}
	macSuppressWarning( substHandle, FALSE );
	strcpy( substEcVers, buff );
    }

    if ( (substEcVers[0] != '$') && (substEcVers[0] != '?') )
	    sprintf( search, "qfix:epcom/%s", substEcVers );
    /*
       See Aug 24,2006 comment below.
    else
    */
	sprintf( search, "qfix:epcom/default" );
    /* if defined (so first character is no longer "$"), use in search
       path for fopenData() */
    if ( (substVersion[0] != '$') && (substVersion[0] != '?') )
	sprintf( search, "%s:%s", search, substVersion );

    /* if not, assume that file name is specified as "$(version)/data/xxx" */
    /* Aug 24,2006 with release 6-0-0, A. Honey changed this to always check
       ../dcs/default after any attempt at a version. This is because ../dcs/<version>
       no longer exits as each subsystem is separated below dcs and each of those
       subsystems has the version number as well as there own default link 
    else
    */
	sprintf( search, "%s:default", search );
#endif

    /* because of DCS reorg split, . dir was added */
    sprintf( search, "%s:.", search );
    
    /* open input file (stdin if not supplied) */
    if ( file == NULL ) {
	fd = stdin;
    }
    else {
#ifdef VXWORKS
      epicsPrintf("pvload->work->FOPEN for %s <%s>\n",search,file);
      epicsPrintf("search path length %d\n",strlen(search));
#endif
	fd = FOPEN( file, "r", search );
	if ( fd == NULL ) {
	    epicsPrintf( "%s: can't open %s for read in search path: %s\n",
                         cmd, file, search );
	    status = -1;
	    goto error;
	}
    }

    /* for pvsave, open output file (stdout if not supplied) and handle
       truncation, append and "fail if not empty" options */
    if ( isPvload || outFile == NULL ) {
	outFd = stdout;
    }
    else {
        char *type;

	/* if OPT_FAIL flag is set, fail if file exists */
	if ( flags & OPT_FAIL ) {
	    outFd = FOPEN( outFile, "r", search );
	    if ( outFd != NULL ) {
		( void ) fclose( outFd );
		epicsPrintf( "%s: output file %s exists and -f specified\n",
			     cmd, outFile );
		status = -1;
		goto error;
	    }
	}

	/* set access type based on OPT_TRUNCATE */
	type = ( flags & OPT_TRUNCATE ) ? "w+" : "a+";
	outFd = FOPEN( outFile, type, search );
	if ( outFd == NULL ) {
	    epicsPrintf( "%s: can't open %s for write\n", cmd, outFile );
	    status = -1;
	    goto error;
	}
    }

    /* use the standard EPICS incantation to reset yacc input, initialize
       the library, parse the input, and shut down the library */
    if ( !count++ )
	yyin = fd;
    else {
#ifdef VXWORKS
/*
      logMsg("yyrestart\n",0,0,0,0,0,0);
*/
      epicsPrintf("yyrestart\n");
#endif
      yyrestart( fd );
    }

    line_num = 1;

#ifdef VXWORKS
/*
     logMsg("pvloadInitialize\n",0,0,0,0,0,0);
*/
     epicsPrintf("pvloadInitialize\n");
#endif
    pvloadInitialize( isPvload, substHandle, outFd, flags );
#ifdef VXWORKS
/*
      logMsg("yyparse\n",0,0,0,0,0,0);
*/
      epicsPrintf("yyparse\n");
#endif
    
    status = yyparse();
#ifdef VXWORKS
/*
      logMsg("pvloadShutdown\n",0,0,0,0,0,0);
*/
      epicsPrintf("pvloadShutdown\n");
#endif
    pvloadShutdown();

    /* close files (if they were opened) */
    if ( fd != stdin )
	( void ) fclose( fd );
    if ( outFd != stdout )
	( void ) fclose( outFd );

    /* jump here on error; tidy up */
error:

    /* free substution data if a substitution string was supplied */
    if ( substHandle != NULL )
        ( void ) macDeleteHandle( substHandle );

    /* decide whether to abort the shell script (vxWorks only) */
#ifdef vxWorks
    if ( ( flags & OPT_ABORT ) && status != 0 )
	shellScriptAbort();
#endif

    /* return status */
    return status;
}

/* Replacement error handler */
static int yyerror( char *str )
{
    fprintf( stderr, "\nError line %d: %s \"%s\"\n", line_num, str, yytext );
    return 0;
}
